### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by dlecan** [robyf/google-chat-linux#1]
Hello,

I'd like to try this application, but I don't how to :-)
Can you give pointers to any setup guides or installation tutorials ?

Thank you

**Comment by robyf** [comment]
You should download the latest .deb file from the releases section and install it following the instructions here, for example: https://unix.stackexchange.com/questions/159094/how-to-install-a-deb-file-by-dpkg-i-or-by-apt

Note that this works only on Debian Linux or derivatives (Ubuntu, Mint, etc).

**Comment by dlecan** [comment]
So simple, I haven't seen released files.
I propose #2 to improve readme file.
