### ISSUE TITLE
requirement to port this to archlinux

### ISSUE THREAD

**Issue by squalou** [robyf/google-chat-linux#5]
Hi,

I ould be interested in porting this to archlinux.
At first sight it's an 'electon' app.

What do you think would be required to have this work on a not-debian based distro ?
(Worded differently : what (to your knowledge) is thightly related to debian-based distro.)

thanks for any advice !

**Comment by robyf** [comment]
Hi,

It's an electron app, yes. The only thing needed would be to find an npm module that packages electron apps into rpm and test it. I don't myself use anything else than debian so I couldn't really test anything like that.

But if you'd like to contribute it would be more than welcome!

**Comment by squalou** [comment]
Good news : I do have a PKGBUILD file that does the job.
It' a bit ugly because I don't know npm enough : I manually strip unneeded dependencies. (those broght by te fact that electron itself is declared as a required dependency).

I'll push that to a git repo quickly so that you can have a look

**Comment by squalou** [comment]
https://github.com/squalou/google-chat-linux-git

please tell what license should be used and what 'attribution' you would like

**Comment by squalou** [comment]
and it's my first small contribution to archlinux ;)
https://aur.archlinux.org/packages/google-chat-linux-git/
