### ISSUE TITLE
notification warning : icon change in tray

### ISSUE THREAD

**Issue by squalou** [robyf/google-chat-linux#6]
I'm using the app on archlinux with gnome 3 desktop.
The 'tray' icon is displayed.
Notifications through the native 'notification mechanism' of gnome works.

But the icon in tray does not change. Is it on purpose ? Would it be possible to have it change somehow ?
(like, red when something new happens)

slack client is built on electron too and does it, but I have no idea what google chat would require to do so.

thanks !

**Comment by robyf** [comment]
It changes for me on mate desktop: green when there are no messages, blue for unread messages, red for "attention" messages and gray when offline.

Maybe there is something a bit weird on the way gnome 3 handles updating of tray icons, I would have to investigate it but I don't know when I'll have time...

**Comment by squalou** [comment]
I'll check again with 'direct' messages tomorrow. I only had the opportunity to test with a 'bot' and maybe the behaviour is not the same when one is ont the dorect lessage recipient.

**Comment by squalou** [comment]
confirmed : it works with 'regular' messages. Closing.
